// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using coleta_residuos.Data.Contexts;

#nullable disable

namespace coleta_residuos.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("coleta_residuos.Models.AlertaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlerta")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("PontoColetaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("Resolvido")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("Id");

                    b.HasIndex("PontoColetaId");

                    b.ToTable("Alertas", (string)null);
                });

            modelBuilder.Entity("coleta_residuos.Models.ColetaAgendadaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAgendada")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("PontoColetaId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("PontoColetaId");

                    b.ToTable("ColetasAgendadas", (string)null);
                });

            modelBuilder.Entity("coleta_residuos.Models.EventoColetaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("PontoColetaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("QuantidadeKg")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("PontoColetaId");

                    b.ToTable("EventosColeta", (string)null);
                });

            modelBuilder.Entity("coleta_residuos.Models.PontoColetaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacidadeMaximaKg")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("PontosColeta", (string)null);
                });

            modelBuilder.Entity("coleta_residuos.Models.PontoColetaResiduoModel", b =>
                {
                    b.Property<int>("PontoColetaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ResiduoId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("PontoColetaId", "ResiduoId");

                    b.HasIndex("ResiduoId");

                    b.ToTable("PontoColetaResiduo", (string)null);
                });

            modelBuilder.Entity("coleta_residuos.Models.ResiduoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("Residuos", (string)null);
                });

            modelBuilder.Entity("coleta_residuos.Models.AlertaModel", b =>
                {
                    b.HasOne("coleta_residuos.Models.PontoColetaModel", "PontoColeta")
                        .WithMany()
                        .HasForeignKey("PontoColetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PontoColeta");
                });

            modelBuilder.Entity("coleta_residuos.Models.ColetaAgendadaModel", b =>
                {
                    b.HasOne("coleta_residuos.Models.PontoColetaModel", "PontoColeta")
                        .WithMany()
                        .HasForeignKey("PontoColetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PontoColeta");
                });

            modelBuilder.Entity("coleta_residuos.Models.EventoColetaModel", b =>
                {
                    b.HasOne("coleta_residuos.Models.PontoColetaModel", "PontoColeta")
                        .WithMany("EventosColeta")
                        .HasForeignKey("PontoColetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PontoColeta");
                });

            modelBuilder.Entity("coleta_residuos.Models.PontoColetaResiduoModel", b =>
                {
                    b.HasOne("coleta_residuos.Models.PontoColetaModel", "PontoColeta")
                        .WithMany("PontosColetaResiduos")
                        .HasForeignKey("PontoColetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("coleta_residuos.Models.ResiduoModel", "Residuo")
                        .WithMany("PontosColetaResiduos")
                        .HasForeignKey("ResiduoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PontoColeta");

                    b.Navigation("Residuo");
                });

            modelBuilder.Entity("coleta_residuos.Models.PontoColetaModel", b =>
                {
                    b.Navigation("EventosColeta");

                    b.Navigation("PontosColetaResiduos");
                });

            modelBuilder.Entity("coleta_residuos.Models.ResiduoModel", b =>
                {
                    b.Navigation("PontosColetaResiduos");
                });
#pragma warning restore 612, 618
        }
    }
}
