services:
  db:
    container_name: oracle-xe
    image: gvenzl/oracle-xe:21.3.0
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      ORACLE_DATABASE: ${ORACLE_DATABASE}
    volumes:
      - db_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'SELECT 1 FROM DUAL;' | sqlplus system/$${ORACLE_PASSWORD}@localhost/coleta_residuos"]
      interval: 20s
      timeout: 10s
      retries: 10

  api:
    image: stephaniegomes/coleta-residuos:latest
    container_name: coleta-residuos-app
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Development

volumes:
  db_data: