services:
  db:
    container_name: oracle-xe
    image: gvenzl/oracle-xe:21.3.0
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      ORACLE_DATABASE: ${ORACLE_DATABASE}
    volumes:
      - db_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "bash", "-c", "sqlplus -v > /dev/null && echo 'Listener is ready' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s

  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: stephaniegomes/coleta-residuos:latest
    container_name: coleta-residuos-app
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  db_data: